import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { UserContextProvider } from "@/context/userContext";
import { Toaster } from "react-hot-toast";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "University Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        <UserContextProvider>
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
